### ISSUE TITLE
Fatal error: [InvalidArgumentException] "@0" is not a valid date.

### ISSUE THREAD

**Issue by sbrl** [clemens-tolboom/uml-generator-php#71]
Here's the full output I  get when I attempt to run this tool:

```



  [InvalidArgumentException]
  "@0" is not a valid date.



generate:json [-s|--skip="..."] [-o|--only="..."] input output



```

 - **OS**: Windows 10
 - **`php --version`**: `PHP 5.6.25 (cli) (built: Aug 18 2016 11:39:11)`

**Comment by clemens-tolboom** [comment]
@sbrl what is your command?

I tried `bin/uml-generator-php generate:json ./src /tmp/output` without trouble.

**Comment by sbrl** [comment]
Huh. that command appears to work. I must have done something strange.
